ForceSinglePlayerClient: false
ForceSinglePlayerClientKickMessage: This server requires Spoutcraft! http://www.spout.org
AuthenticateSpoutcraft: true
AuthenticateTicks: 200
AllowEntityLabelCheat: false
AllowClearWaterCheat: false
AllowCoordsCheat: true
AllowSkyCheat: false
AllowStarsCheat: false
AllowTimeCheat: false
AllowVoidFogCheat: false
AllowWeatherCheat: false
