name: RockyPlugin
version: ${buildNumber}
description: RockyPlugin is a plugin for Bukkit-based servers and a Minecraft client mod system that exposes new API for other plugins to utilize.
author: VolumetricPixels
website: http://www.volumetricpixels.com

main: com.volumetricpixels.Rocky
load: startup
mcversion: ${minecraftVersion}

commands:
    rocky:
        aliases: [rockycommand, rockycmd, rkcmd]
        description: Various Rocky commands.
        usage: |
            Usage: /<command> version [player]
            Usage: /<command> verify [motd]

permissions:
    rocky.plugin.force:
        description: Forces players to join with Rocky even if the server doesn't force Rocky in the config.
        default: false